### ISSUE TITLE
Add all mentors to the private mentor slack channel

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#1]
Channel: https://mozfest.slack.com/messages/GCNUXHPB7/details/

List of mentors: https://docs.google.com/spreadsheets/d/11P354PRyOCXbrvOaVJ3emTXtH8gyfvPhcFR63d4ezZg/edit#gid=1888177383

**Comment by abbycabs** [comment]
Folks are also asking for invites here: https://mozfest.slack.com/messages/CFBU06YUF/

@marcwalsh is this something you have time for this week?

**Comment by marcwalsh** [comment]
@acabunoc - I've just invited those who asked for access on the OL7 channel. 

Do we have Slack handles for everyone else, or will they need adding to the Slack instance first?

**Comment by abbycabs** [comment]
Many of them will already be in slack if they participated in OL6, but you'll have a few that haven't joined yet. I didn't ask for their slack handles at registration (that would have been a good idea!). But I did email them all the invitation link yesterday.

Thanks Marc!

**Comment by marcwalsh** [comment]
I've added everyone who is currently on Slack. Below is the list I pulled from the spreadsheet in the first comment - those marked with N have not yet joined Slack.

https://docs.google.com/spreadsheets/d/1JOvlc14H6c8h9ViSDrvtYm44VzNMNOW_EDpB3WJbTXY/edit#gid=1888177383

**Comment by abbycabs** [comment]
I say we mark this as done & close the issue! Mentors can let us know if they want an invite :)
