### ISSUE TITLE
Put together summary of feedback from OL6

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#11]

**Comment by chadsansing** [comment]
See also: https://docs.google.com/document/d/1SGNP6jtvy_Th874rOR3DZGgSh7BOEioIEbeK5EhFP5Y/edit#heading=h.2vdqjk24ov1

**Comment by abbycabs** [comment]
OL5 review: https://docs.google.com/presentation/d/1MbRe4NkwokAcNM7on8HkxHEop9IhrbXC5XSB8aUpHQ8/edit?usp=drive_web&ouid=113263149988286049053

**Comment by abbycabs** [comment]
Looks great, thanks @marcwalsh 
https://docs.google.com/presentation/d/1jokajj_VF0TpT84oXaZT1SB8BYW1uxIWd8HaHVsby7w/edit?ts=5c3cd5da#slide=id.g37695b23f5_0_10
