### ISSUE TITLE
Email all mentors Jan 18

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#14]
Hey @marcwalsh, can you send an email to all mentors sometime tomorrow? [All registered mentors](https://docs.google.com/document/d/12V4HnkPY1JNMIam_jwprXMwS5WKXKU1rIqxcoScHV0g/edit#heading=h.rdxvwxm9ophz)

Subject: [OL7 Mentors] Last day for mentee selection!
Rough content:
* Reminder: it's the last day to select your mentees
  * selection instructions (cut/paste from [this email](https://docs.google.com/document/d/12V4HnkPY1JNMIam_jwprXMwS5WKXKU1rIqxcoScHV0g/edit#heading=h.rdxvwxm9ophz))
* Here are the mentor orientation recordings & notes
  * project track 
    * recording: https://youtu.be/06AIe0qtoUY
    * notes: https://goo.gl/4xosQe
  * culture track
    * recording: @chadsansing can you comment with link?
    * notes: https://docs.google.com/document/d/1ANl30ePPVCUvbERLsZ1e-pabAMJUFz0zLR-36RMJiWY/edit#

**Comment by chadsansing** [comment]
@acabunoc, here it is:

https://drive.google.com/file/d/1uLmU5zvRvJDxYQj1n6A5zDcOy5_GByIG/view?usp=sharing

**Comment by marcwalsh** [comment]
Thanks @chadsansing and @acabunoc - this has been sent! 🥳
