### ISSUE TITLE
Send acceptance emails

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#15]
- [x] Install [Yet Another Mail Merge](https://yet-another-mail-merge.com/) (@marcwalsh - I sent you an invite that will get us both 50 more emails / day, pls use!)
- [x] Make an email draft in gmail using the content in [this email template](https://docs.google.com/document/d/1fw9p81u5yh7wIBvbmTDzmrjRYPOKq9PpXg0Wj5-fLg4/edit).
- [x] Go to the [Acceptance Email spreadsheet](https://docs.google.com/spreadsheets/d/1hdWvyedaEoFzcuzWnKLe0XeBLHDmUaXqeQjPx0cnPPs/edit#gid=92402457) - stay on the first sheet. This sheet automatically reads in the results from the sheet mentors are using to select mentees (http://mzl.la/ol7-short-list) 
- [x] Filter by Status (Column J) -- 'accepted' (we only want to send this email to accepted applicants)
<img width="311" alt="screen shot 2019-01-18 at 12 37 49 am" src="https://user-images.githubusercontent.com/617994/51367591-4f1bba80-1ab9-11e9-99b4-9d2ed1bd25f7.png">

- [x] Go to 'Add-ons' -> 'Yet Another Mail Merge' -> 'Start Mail Merge'
<img width="423" alt="screen shot 2019-01-18 at 12 34 12 am" src="https://user-images.githubusercontent.com/617994/51367477-d74d9000-1ab8-11e9-9607-91a70b6469c3.png">

- [x] Click 'Continue'
- [x] Select "Mozilla Open Leaders 7: Congratulations! (Register by Jan 25)" from the "Email Template" dropdown. 
<img width="526" alt="screen shot 2019-01-18 at 12 38 29 am" src="https://user-images.githubusercontent.com/617994/51367615-6b1f5c00-1ab9-11e9-984b-a8ccf9ccb52d.png">

- [x] This is a good time to test by clicking 'Receive test email'.
- [x] If all looks good, click on 'Send XX emails'!

I'll ping you when I'm at my desk in the morning in case anything needs clarification. If you're interested in some of the google sheets formulas to get this, I can walk you through it in a quick call

**Comment by marcwalsh** [comment]
Thanks @acabunoc - I've sent through the first 100 emails (up to my allowance for the day). They are marked as EMAIL_SENT on the spreadsheet!

**Comment by abbycabs** [comment]
sent the last few! I'll do one more batch before I leave today

**Comment by abbycabs** [comment]
did a batch just now! There are still 16 mentors choosing. @marcwalsh can you send one last batch of acceptances Monday? Will leave this open till then.

**Comment by marcwalsh** [comment]
Sent the final acceptances - I think we're good to close :)
