### ISSUE TITLE
send wait list emails / independant project

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#17]
Email content: https://docs.google.com/document/d/1fw9p81u5yh7wIBvbmTDzmrjRYPOKq9PpXg0Wj5-fLg4/edit#heading=h.57v3i3fbw9cr
Filter sheet for 'wait list' (column J): https://docs.google.com/spreadsheets/d/1hdWvyedaEoFzcuzWnKLe0XeBLHDmUaXqeQjPx0cnPPs/edit#gid=92402457

Use YAMM again! set reply-to leadopen@mozillafoundation.org

**Comment by abbycabs** [comment]
@marcwalsh let me know if you can get to this today! If not, I can take of this later

**Comment by marcwalsh** [comment]
All sent! :) Closing...
