### ISSUE TITLE
mentor followup

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#20]
Follow up with mentors whose mentees did not register. See if they want to pick up anyone from the wait list

@marcwalsh let us know if you have time for this on Wednesday, otherwise I can take a look

cc: @chadsansing

**Comment by abbycabs** [comment]
one thing to flag - it looks like janice hasn't registered. might be worth following up with her personally before reassigning her mentor

**Comment by abbycabs** [comment]
emailed janice directly

**Comment by marcwalsh** [comment]
Evelyne was also having some issues with registering and I've been in contact with here, so I won't email their mentor yet. I have sent emails to the other two mentors.

**Comment by marcwalsh** [comment]
I'm going to close this for now, and reopen if I need contact anyone else. 🎈
