### ISSUE TITLE
Schedule meetings with 'independant projects'

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#21]
We should have a Week 1 call with all the current wait list projects. Once #20 is done, we should schedule check-ins with all the independent projects.

@chadsansing - can you handle all the culture track ones & I'll do project track?

Plan is to treat them like normal mentorship calls and hand the doc to the new mentor when someone picks them up.

**Comment by chadsansing** [comment]
Email sent to culture track independent project leads, 30 January 2019. cc-ed to @acabunoc & @marcwalsh.

**Comment by abbycabs** [comment]
ah, sorry your group got doubled emailed. I sent this to *all* independent projects.

I'm going to wait a day or so before scheduling calls with the project track waitlist -- I expect a few will get picked up.

***

Hi there,

I'm sending a quick note to all the independent projects in OL7 to let you know that we haven't forgotten about you! As independent projects, you weren't matched with a mentor during our review process, but you have been placed on the mentor wait list.

We recently closed registration, so there's a good chance your project will get picked up by a mentor soon. Later this week, either an organizer or your new mentor will reach out to schedule your Week 1 call at a time that works for both of you.

Thanks for your patience -- we're thrilled to have you in OL7!
Abby

**Comment by abbycabs** [comment]
scheduled with project track! Closing for now
