### ISSUE TITLE
send week 2 emails

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#25]
[Project Track](https://docs.google.com/document/d/1yI2fNWcbsH7TwxI99tOHasvzFC50bPoFuep927Sc5GQ/edit#heading=h.eteavjhsvxee) - all links and copy have been updated for OL7, ready to send!

[Culture Track](https://docs.google.com/document/d/1P8JhHx2Dzh-4-zeHHoaPZDPzn5bOKz8OYInYQKWnbUQ/edit) - may need to be updated

cc: @chadsansing 

Send by EOD Monday

**Comment by marcwalsh** [comment]
Sent to:

- [x] Project Track
- [x] Culture Track

**Comment by chadsansing** [comment]
@marcwalsh, I think these are pretty good to go minus any comments indicating missing links.

**Comment by marcwalsh** [comment]
Great thanks @chadsansing I'll get these sent out straight away! :)

M

**Comment by marcwalsh** [comment]
All sent... I'll close this and see you at the same time next week! 💃

**Comment by abbycabs** [comment]
@marcwalsh if it helps, in the past I've used Boomerang to schedule these

**Comment by marcwalsh** [comment]
@acabunoc - Thanks, yeah I can do it on AirMail as well, but I always try to avoid scheduling these sorts of emails just in case something requires a change last minute. - It only takes a few minutes to get set up.
