### ISSUE TITLE
Send out notification emails - people who miss cohort or mentorship calls

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#26]
Attendance Sheet: https://docs.google.com/spreadsheets/d/1If5CtQ90u_x0w4PLD8UybB2Yl9Kcxtua2XjWsmbgD5c/edit#gid=1920399517

For all cohorts
- **update attendance** for 'Week 2' (Column H). Use the roll call in each of the cohort call notes. This can be a simple true/false
  - [x] [A](http://mzl.la/ol7-cohort-a)
  - [x] [B](http://mzl.la/ol7-cohort-b)
  - [x] [C](http://mzl.la/ol7-cohort-c)
  - [x] [D](http://mzl.la/ol7-cohort-d)
  - [x] [Cohort E week 2 notes w/ roll call](https://docs.google.com/document/d/19jIlXR1RDTXnkbgYdj1YVButm8AXoKNUEFbzTdaO3P4/edit#heading=h.4oasu54wlszp)
  - [x] [Cohort F week 2 notes w/ roll call](https://docs.google.com/document/d/1gDstjeMJGRrDUCVm4dznEeUz4BBSlb-laZaNrDB56kg/edit#heading=h.4oasu54wlszp)

- [x] **send notifications** - cc Abby & Chad in the draft (then we'll be cc'ed in all the emails). Here's the [email content](https://docs.google.com/document/d/1LyapBXMP59cuQt7WAWQU85xMgVowdDxqvb_IrOVE65g/edit#) 3 scenarios outlined:
  - missed week 1
  - missed week 2
  - missed week 1 & 2
Filter columns G & H appropriately for the 3 scenarios. Consider mentees as 'missed week 1' if the mentor selected 'mentee did not show' in the tracking sheet.

Timeline: let's try to send these out by EOD Friday!

**Comment by abbycabs** [comment]
I'm adding the Week 2 recordings and notes in the attendance sheet for the mail merge. Will update here once it's ready!

**Comment by abbycabs** [comment]
filled out everything except for cohort D recording. IF the cohort D recording shows up here, then you can paste it in: https://docs.google.com/spreadsheets/d/1ZxwdIIvSbDVCWb6x0sQHXaFr9xZlErcqj9rglgNPxOQ/edit#gid=728751204

**Comment by chadsansing** [comment]
Would prefer to handle all logistics the same way program-wide :)

- [Cohort E week 2 notes w/ roll call](https://docs.google.com/document/d/19jIlXR1RDTXnkbgYdj1YVButm8AXoKNUEFbzTdaO3P4/edit#heading=h.4oasu54wlszp)
- [Cohort F week 2 notes w/ roll call](https://docs.google.com/document/d/1gDstjeMJGRrDUCVm4dznEeUz4BBSlb-laZaNrDB56kg/edit#heading=h.4oasu54wlszp)

@acabunoc, can you add E & F to the checklist in the issue?

**Comment by abbycabs** [comment]
I've added the cohort D recording link to the attendance sheet: https://docs.google.com/spreadsheets/d/1If5CtQ90u_x0w4PLD8UybB2Yl9Kcxtua2XjWsmbgD5c/edit#gid=1920399517

@chadsansing can you add links to E & F recordings?

**Comment by chadsansing** [comment]
Done.

**Comment by abbycabs** [comment]
updated top comments to reflect both tracks

**Comment by marcwalsh** [comment]
I've hit my quota for the day, @acabunoc is going to send through the last few emails instead. I'll close this now. :)

**Comment by abbycabs** [comment]
sent the last 4 emails!
