### ISSUE TITLE
Week 3 email

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#27]
Issue to collect info for the Week 3 Monday email.

Project Track: https://docs.google.com/document/d/1yI2fNWcbsH7TwxI99tOHasvzFC50bPoFuep927Sc5GQ/edit#heading=h.j7p607bgtkdl
^ should be good to send out to the same group as before

cc @chadsansing

**Comment by chadsansing** [comment]
Culture track ready [here](https://docs.google.com/document/d/1P8JhHx2Dzh-4-zeHHoaPZDPzn5bOKz8OYInYQKWnbUQ/edit#).

**Comment by marcwalsh** [comment]
All sent! 🥳

See you at the same time next week!
