### ISSUE TITLE
Update mentor/mentee

### ISSUE THREAD

**Issue by chadsansing** [MozillaFestival/open-leaders-planning#28]
@marcwalsh, let's be sure to loop back later this week to update the mentor/mentee pairing we're discussing on Slack.

cc @acabunoc

**Comment by abbycabs** [comment]
Looks like original mentee never registered, so the new match is a bit easier than my original comments!

Thread here: https://mozfest.slack.com/archives/GCNUXHPB7/p1549888090001200

**Comment by chadsansing** [comment]
Word.
