### ISSUE TITLE
remove folks that don't reply to 'confirming participation' email by Wednesday

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#29]
If any of the people that received a 'confirming participation' email don't reply to confirm their participation:
* Send a notification on Thursday that they've been removed from OL7 (cc mentor, Abby & Chad) - @acabunoc will add an email template to this issue
*  Update their status to 'withdrew' in the [Attendance list](https://docs.google.com/spreadsheets/d/1If5CtQ90u_x0w4PLD8UybB2Yl9Kcxtua2XjWsmbgD5c/edit#gid=1920399517), and remove them from any email lists you may have
* Remove them from the tracking sheet
* Remove them from the website (@acabunoc can help with wagtail)
* If the entire team has been removed from OL7: send the mentor the waitlist projects if they're interested in mentoring someone else

@acabunoc: share template for email, show Marc how to remove someone from the website
@marcwalsh: send emails, update sheets

cc: @chadsansing

**Comment by marcwalsh** [comment]
@acabunoc - How do I get login details for wagtail? I haven't had access before! :)

**Comment by abbycabs** [comment]
@marcwalsh login with Google! As staff, you should have edit rights 
http://foundation.mozilla.org/cms

**Comment by abbycabs** [comment]
Rough template for removing from OL7
https://docs.google.com/document/d/1LyapBXMP59cuQt7WAWQU85xMgVowdDxqvb_IrOVE65g/edit#heading=h.2m8m2uw2g7p7

**Comment by marcwalsh** [comment]
Emails sent and Wagtail updated!
