### ISSUE TITLE
Scheduling Mentor Training calls

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#30]
I can facilitate the standard GROW / mentor skills one we've in the past when I'm back from PTO (maybe Week 9?).

Chad, would you be up for facilitating something while I'm away? (Week 5 or 7)?

cc: @chadsansing & @marcwalsh

**Comment by chadsansing** [comment]
Yes - week 7 maybe?

**Comment by abbycabs** [comment]
Week 7 is good! 2 mentor trainings again? Want to pick 2 times that week and I'll mirror it on week 9?

**Comment by chadsansing** [comment]
How about 8 AM ET on Tuesday, 12 March 2019, and 2 PM ET on Thursday, 14 March 2019?

@marcwalsh, can you send all the mentors invites to 1-hour long meetings at those dates and times? If you then share ownership with me, I will add the Zoom room and agenda later.

**Comment by abbycabs** [comment]
@marcwalsh ditto for week 9

**Comment by abbycabs** [comment]
Who to invite:
* All [OL7 Mentors](https://docs.google.com/spreadsheets/d/11P354PRyOCXbrvOaVJ3emTXtH8gyfvPhcFR63d4ezZg/edit#gid=1888177383)
* All [Experts who checked off Mentor Training](https://docs.google.com/spreadsheets/d/1xCe2xcXMnCBydDvsOT3UBkcr6vSWBdMWtx0NmB8ujJ0/edit#gid=2060343609) - Column D

**Comment by marcwalsh** [comment]
Will send these all out tomorrow Friday 22nd!

**Comment by marcwalsh** [comment]
All sent! :)
