### ISSUE TITLE
Week 4 emails

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#31]
Email templates
- [project track](https://drive.google.com/open?id=1yI2fNWcbsH7TwxI99tOHasvzFC50bPoFuep927Sc5GQ)
- [culture track](https://docs.google.com/document/d/1P8JhHx2Dzh-4-zeHHoaPZDPzn5bOKz8OYInYQKWnbUQ/edit)

- [x] Add content for project track email - @acabunoc
- [x] update content for culture track email - @chadsansing & @marcwalsh
- [x] Send project track & culture track email on Monday Feb 18 - @marcwalsh

... For future weeks I'm thinking of creating one issue with a checklist for the rest of the program. @marcwalsh would that work for you?

**Comment by abbycabs** [comment]
Week 4 email is ready!

**Comment by chadsansing** [comment]
@marcwalsh, Week 4 copy is ready on the [doc](https://docs.google.com/document/d/1P8JhHx2Dzh-4-zeHHoaPZDPzn5bOKz8OYInYQKWnbUQ/edit#); if you can make the cohort channels and add them to the Week 4 email (at the bottom) before sending, that would be awesome. If not, we can share this week, email reminders next week.

- Cohort E: the Envited (#envited)
- Cohort F: Design & Concur (#design-and-concur)

**Comment by marcwalsh** [comment]
@acabunoc - totally fine to have an issue for all weeks!

**Comment by marcwalsh** [comment]
Both sent! See you next week 🤖

**Comment by marcwalsh** [comment]
@acabunoc - I've made issue 32 to track weekly emails!
