### ISSUE TITLE
Send out missed meeting notifications

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#33]
Attendance Sheet: https://docs.google.com/spreadsheets/d/1If5CtQ90u_x0w4PLD8UybB2Yl9Kcxtua2XjWsmbgD5c/edit#gid=1920399517

For all cohorts
- **update attendance** for 'Week 4' (Column J). Use the roll call in each of the cohort call notes. This can be a simple true/false
  - [x] [A](http://mzl.la/ol7-cohort-a)
  - [x] [B](http://mzl.la/ol7-cohort-b)
  - [x] [C](http://mzl.la/ol7-cohort-c)
  - [x] [D](http://mzl.la/ol7-cohort-d)
  - [x] [E](https://drive.google.com/open?id=1InMw-zRFwo2G3EY8dxThec7uzocJdyqsFz9jYB9Iwq0)
  - [x] [F](https://drive.google.com/open?id=1i70_QnNsbIiDTyphSpOXi0d_EJ-X89XW9akU6s1nmTQ)

- [x] Add week 4 recordings and notes links to the [attendance sheet](https://docs.google.com/spreadsheets/d/1If5CtQ90u_x0w4PLD8UybB2Yl9Kcxtua2XjWsmbgD5c/edit#gid=1920399517) (Columns M & N) - @acabunoc and @chadsansing 
- [x] Update [email content](https://docs.google.com/document/d/1LyapBXMP59cuQt7WAWQU85xMgVowdDxqvb_IrOVE65g/edit#) for week 4 - @acabunoc (@chadsansing to review for culture track)

- [x] **send notifications** - cc Abby & Chad in the draft (then we'll be cc'ed in all the emails). Here's the [email content](https://docs.google.com/document/d/1LyapBXMP59cuQt7WAWQU85xMgVowdDxqvb_IrOVE65g/edit#)

Timeline: let's try to send these out by EOD Friday!

**Comment by chadsansing** [comment]
Updated culture track attendance, links, & Week 5 email content.

**Comment by abbycabs** [comment]
pinged Cohorts A-D mentors who haven't filled out the tracking sheet
Added week 4 recording and notes links

**Comment by abbycabs** [comment]
Updated email templates - 
https://docs.google.com/document/d/1LyapBXMP59cuQt7WAWQU85xMgVowdDxqvb_IrOVE65g/edit#

Flagging @chadsansing for review

**Comment by chadsansing** [comment]
+r

**Comment by abbycabs** [comment]
@marcwalsh sent most of the emails -- I sent the rest after he hit his YAMM quota. Closing!
