### ISSUE TITLE
midterm survey review

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#36]
Participants: https://docs.google.com/forms/d/11KXVzEgRc8Hj-DIPZF-Ea9ZWRZxopsmGJGAqxn-z4PI/edit

Mentor: https://docs.google.com/forms/d/1ab_S815u6vG3QqkcfWOLKBAvAEy93HA4S96c_o57aR8/edit

@chadsansing please review & make edits before the Week 7 email goes out

**Comment by chadsansing** [comment]
+r

No revisions/suggestions at this time. 

cc @marcwalsh

**Comment by marcwalsh** [comment]
Thanks! All sent 👍
