### ISSUE TITLE
mentor midterm survey email

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#37]
On Monday March 11 (Week 7), send all the mentors the midterm survey

***

to: chad & abby
bcc: all mentors
Subject: [OL7 Mentors] Survey (due March 20)
Hello Mentors,

We'd love to hear how mentorship is going & how we can better support you. Please complete this midterm survey by March 20:
https://goo.gl/forms/2O7QltlqbDgzLxwR2

**Mentor Training Reminder:**
There are two upcoming mentors trainings. Check your calendar for details.

Thanks,
Marc

**Comment by marcwalsh** [comment]
Sent to all mentors! ✉️
