### ISSUE TITLE
Thu Feb 28: Remove participants that don't confirm participation

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#38]
Same as #29, but for this new batch

For everyone that received a 'confirming participation' email don't reply to confirm their participation:
- [x] Send a notification on Thursday that they've been removed from OL7 (cc mentor, Abby & Chad). Use the same template.
- [x] Update their status to 'withdrew' in the [Attendance list](https://docs.google.com/spreadsheets/d/1If5CtQ90u_x0w4PLD8UybB2Yl9Kcxtua2XjWsmbgD5c/edit#gid=1920399517), and remove them from any email lists you may have
- [x] Remove them from the tracking sheet - http://mzl.la/ol7-tracking-sheet
- [x] Remove them from the website (@acabunoc can help with wagtail)
- [x] If the entire team has been removed from OL7: send the mentor the waitlist projects if they're interested in mentoring someone else

cc: @chadsansing

**Comment by marcwalsh** [comment]
All sent! Closing...
