### ISSUE TITLE
midterm survey reminders

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#39]
Email content: https://docs.google.com/document/d/1LyapBXMP59cuQt7WAWQU85xMgVowdDxqvb_IrOVE65g/edit#heading=h.lgalzuqoj3rj

I've added a 'Midterm' column (Column J) in the Attendance Sheet. 
Attendance Sheet: Attendance Sheet: https://docs.google.com/spreadsheets/d/1If5CtQ90u_x0w4PLD8UybB2Yl9Kcxtua2XjWsmbgD5c/edit#gid=1920399517

- Review [email content](https://docs.google.com/document/d/1LyapBXMP59cuQt7WAWQU85xMgVowdDxqvb_IrOVE65g/edit#heading=h.lgalzuqoj3rj) - @chadsansing 
- Send notifications to everyone who hasn't completed the midterm survey- cc Abby & Chad in the draft (then we'll be cc'ed in all the emails). Here's the [email content](https://docs.google.com/document/d/1LyapBXMP59cuQt7WAWQU85xMgVowdDxqvb_IrOVE65g/edit#heading=h.lgalzuqoj3rj) - @marcwalsh 

@marcwalsh do you have time to get these out this week? If not, I can handle this

**Comment by marcwalsh** [comment]
@acabunoc I've sent out as many as my quota allows, around half remain. Are you okay to send the rest please?

**Comment by marcwalsh** [comment]
I sent the remainer on BCC! Closing :)
