### ISSUE TITLE
Find cohort hosts for project track

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#4]
- [x] update cohort host role for OL7
- [x] draft email - invitation to host
- [x] Reach out to previous hosts
- [x] Reach out to new hosts
- [x] add cohort hosts to website

**Comment by abbycabs** [comment]
New role description here: https://goo.gl/ubD3kN

flagging @chadsansing for optional review (I know you've already communicated with your hosts)
https://docs.google.com/document/d/1RADYnN_z8hBKSypUD2QsFM-mNMVsPIhZBIB7DmkgFRA/edit#

**Comment by abbycabs** [comment]
email draft
https://docs.google.com/document/d/1_QFBVm93a_NGXh1UTy9jgcQQHLU54sazoiDd_pqd3rc/edit#

**Comment by abbycabs** [comment]
Sent out invitations to OL6 hosts, will wait to see who is interested and available for which cohorts before filling in gaps with new hosts.

**Comment by abbycabs** [comment]
I'll be updating this comment with hosts as we find them:

Cohort A: Priyanka Nag & Rob Schaefer
Cohort B: Gracielle Higino & Lucia Trias
Cohort C: David Bild & Heather Stone
Cohort D: Yo Yehudi & Grant Vousden-Dishington

**Comment by chadsansing** [comment]
Cohort E: Aubrie Johnson & Sarah Morris
Cohort F: Meag Doherty & Chad Sansing

**Comment by abbycabs** [comment]
All hosts (finally!) confirmed 🎉 

Cohort A: Priyanka Nag & Rob Schaefer
Cohort B: Gracielle Higino & Lucia Trias
Cohort C: David Bild & Heather Stone
Cohort D: Yo Yehudi & Grant Vousden-Dishington
Cohort E: Aubrie Johnson & Sarah Morris
Cohort F: Meag Doherty & Chad Sansing

Now on to updating the website & hosting guide

**Comment by abbycabs** [comment]
Hosts added to website! 
https://foundation.mozilla.org/en/opportunity/mozilla-open-leaders/round-7/participants/

Closing
