### ISSUE TITLE
Put together mentor orientation agenda

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#5]
* OL7 overview - @acabunoc 
* Some training (20-30min)
  * ideas: making personal connections, culture of gratitude. Would appreciate input from @chadsansing 
* Introduce idea of decentralizing OL/GS - ask mentors to reach out if they're interested

**Comment by chadsansing** [comment]
- Tips for breakout rooms (frequent reminders to hold space for all speakers, reminders of prompts, etc.).
- Check-ins & culture of gratitude rituals.
- Help participants set realistic goals and consider/track learning and growth, as well as deliverable outcomes.
- Be proactive in recruiting experts for mentor meetings.
- Frequently ask what the participant needs from you, acknowledge what you can and cannot do, and help them connect to experts and resources that might help if you cannot.
- Use the agendas or co-create your own, but have an agenda you try to stick to to honor time and preparation. Change when you need to, but have a structure in place to scaffold your time together.

Will add more as ideas occur.

**Comment by abbycabs** [comment]
Starting the agenda doc here: https://goo.gl/4xosQe

Thanks @chadsansing! Will incorporate

**Comment by chadsansing** [comment]
Left a few comments/suggestions to resolve before opening doc.

**Comment by abbycabs** [comment]
updated this to be assigned to both of us -- thanks for your help

**Comment by abbycabs** [comment]
Shortlink for mentor orientation notes: https://goo.gl/4xosQe (I made a copy so previous comments aren't discoverable -- this one is public now)

I'll go ahead and send invites with this agenda. Will revisit next week to flesh it out more.
