### ISSUE TITLE
Create OL7 request experts form

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#7]
- make form @marcwalsh 
- add email magic @acabunoc

Form form OL6
http://mzl.la/ol6-expert-form

**Comment by marcwalsh** [comment]
@acabunoc - here's the form for OL7 (without the email script) 

https://docs.google.com/forms/d/1blo_P4C0IcvJXe_U5_jAImAfkI0Tft5NUDgrZHACikQ/edit

(Saved in the OL7 Draft Documents folder)

:)

**Comment by abbycabs** [comment]
@marcwalsh - any update on the script? Lemme know if you need anything!

**Comment by marcwalsh** [comment]
First thing on my list today!!

**Comment by marcwalsh** [comment]
It's working!! 🎉 🥳

I had a few problems with "TypeError: Cannot call method "toString" of undefined." But managed to figure out that I had an extra space at the end of the questions!

Short link to form is: https://mzl.la/ol7-expert-request

Thanks so much for your help @acabunoc - I'll move the form into the Mentor folder and close the issue.

**Comment by abbycabs** [comment]
👏🎉🙌

**Comment by marcwalsh** [comment]
Closing! :)
