### ISSUE TITLE
Create OL7 featured experts doc

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#9]
Here's the OL6 featured experts doc: http://mzl.la/ol6-featured-experts

Here are all the experts for OL7: https://docs.google.com/spreadsheets/d/1xCe2xcXMnCBydDvsOT3UBkcr6vSWBdMWtx0NmB8ujJ0/edit#gid=2060343609

**Comment by marcwalsh** [comment]
@acabunoc - here's the updated [Featured Experts doc](https://docs.google.com/document/d/1L-J8KdITululpwy0GOC8RgzGnWLftL3s203DJ84xhoA/edit?usp=sharing) with all the extra mentor added (I kept the OL6 mentors in is that correct?)

If it's all okay, I'll move it into the Public Mentors folder and close the ticket.

**Comment by abbycabs** [comment]
Oh! Please remove the OL6 mentors if they didn't sign up again for OL7! Sorry I should have been clearer

**Comment by marcwalsh** [comment]
Ahh okay, easy to fix! :) I'll let you know once it's done

**Comment by marcwalsh** [comment]
I've removed all OL6 experts - it's only those in the doc above who are listed. 

Let me know if this is okay now and I'll close!

**Comment by abbycabs** [comment]
This is great, thanks @marcwalsh! closing
